#!/bin/bash

# Note: the following line should not be modified, and neither the token should
# be repeated in this file because It will be replaced during installation with
# the respective installation prefix.
KW_INSTALL_PREFIX=${KW_INSTALL_PREFIX:-"##KW_INSTALL_PREFIX_TOKEN##"}

KWORKFLOW=${KWORKFLOW:-"kw"}

# Global paths
KW_LIB_DIR=${KW_LIB_DIR:-"$KW_INSTALL_PREFIX/lib/kw"}
KW_SHARE_DOC_DIR=${KW_SHARE_DIR:-"$KW_INSTALL_PREFIX/share/doc/kw/"}
KW_SHARE_MAN_DIR=${KW_SHARE_DIR:-"$KW_INSTALL_PREFIX/share/man"}
KW_SHARE_SOUND_DIR=${KW_SHARE_DIR:-"$KW_INSTALL_PREFIX/share/sound/kw"}
KW_ETC_DIR=${KW_ETC_DIR:-"$KW_INSTALL_PREFIX/etc/kw"}
KW_DATA_DIR=${KW_DATA_DIR:-"$HOME/.kw"}
KW_PLUGINS_DIR=${KW_PLUGINS_DIR:-"$KW_LIB_DIR/plugins"}
KW_CACHE_DIR="$HOME/.cache/kw"

# User data
# TODO: These two variables just introduce more complexity, try to get rid of
# them.
config_files_path=${config_files_path:-"$KW_DATA_DIR"}
statistics_path=${statistics_path:-"$KW_DATA_DIR/statistics"}

# Export external variables required by kworkflow
export KWORKFLOW
. "$KW_LIB_DIR/kw_include.sh" --source-only


function kw()
{
  action="$1"
  shift

  mkdir -p "$KW_CACHE_DIR"

  case "$action" in
    init)
      (
        include "$KW_LIB_DIR/init.sh"

        init_kw
        return "$?"
      )
      ;;
    mount|mo)
      (
        include "$KW_LIB_DIR/vm.sh"

        vm_mount
        local ret="$?"
        alert_completion "kw mount" "$1"
        return "$ret"
      )
      ;;
    umount|um)
      (
        include "$KW_LIB_DIR/vm.sh"

        vm_umount
        local ret="$?"
        alert_completion "kw umount" "$1"
        return "$ret"
      )
      ;;
    up|u)
      (
        include "$KW_LIB_DIR/vm.sh"

        vm_up
      )
      ;;
    build|b)
      (
        include "$KW_LIB_DIR/mk.sh"

        mk_build '' "$@"
        local ret="$?"
        alert_completion "kw build" "$1"
        return "$ret"
      )
      ;;
    deploy|d)
      (
        include "$KW_LIB_DIR/mk.sh"

        kernel_deploy "$@"
        local ret="$?"
        alert_completion "kw deploy" "$1"
        return "$ret"
      )
      ;;
    bd)
      (
        include "$KW_LIB_DIR/mk.sh"

        mk_build && kernel_deploy "$@"
        local ret="$?"
        alert_completion "kw db" "$1"
        return "$ret"
      )
      ;;
    diff|df)
        include "$KW_LIB_DIR/diff.sh"

        diff_manager "$@"
      ;;
    ssh|s)
      (
        include "$KW_LIB_DIR/vm.sh"

        vm_ssh $@
      )
      ;;
    vars)
      (
        include "$KW_LIB_DIR/kw_config_loader.sh"

        show_variables
      )
      ;;
    codestyle|c)
      (
        include "$KW_LIB_DIR/checkpatch_wrapper.sh"

        execute_checkpatch "$@"
      )
      ;;
    maintainers|m)
      (
        include "$KW_LIB_DIR/get_maintainer_wrapper.sh"

        execute_get_maintainer $@
      )
      ;;
    configm|g)
      (
        include "$KW_LIB_DIR/config_manager.sh"

        execute_config_manager "$@"
      )
      ;;
    help|h)
      (
        include "$KW_LIB_DIR/help.sh"

        kworkflow_help
      )
      ;;
    explore|e)
      (
        include "$KW_LIB_DIR/explore.sh"

        explore "$@"
      )
      ;;
    man)
      (
        include "$KW_LIB_DIR/help.sh"

        kworkflow_man
      )
      ;;
    version|--version|-v)
      (
        include "$KW_LIB_DIR/help.sh"

        kworkflow_version
      )
      ;;
    statistics)
      (
        include "$KW_LIB_DIR/statistics.sh"

        statistics "$@"
      )
      ;;
    clear-cache)
        include "$KW_LIB_DIR/mk.sh"

        cleanup
      ;;
    # Subsystems support
    drm)
      (
        include "$KW_LIB_DIR/subsystems/drm/drm.sh"

        drm_manager "$@"
      )
      ;;
    *)
      (
        include "$KW_LIB_DIR/help.sh"

        complain "Invalid option"
        kworkflow_help
        return 1
      )
      ;;
  esac
}

kw "$@"
